/* Run: node tests/volleyball-core.test.cjs */
'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const js=fs.readFileSync(path.join(__dirname,'..','volleyball-core.js'),'utf8'),window={};
vm.runInNewContext(js,{window,Date,JSON,Number,Math,Error,Array,Object,Set,String});
const v=window.CCVolleyballCore;
const lineup=[['1','2','3','4','5','6'],['7','8','9','10','11','12']];
const toArray=x=>Array.from(x);
const c=v.newCourt(1);
assert.equal(c.active.status,'setup');
assert.equal(v.validateLineups(lineup),'');
const repeated=lineup.map(x=>x.slice());repeated[0][3]='3';
assert.match(v.validateLineups(repeated),/ismétlődhet/);
const single=[lineup[0],Array(6).fill('')];
assert.equal(v.validateLineups(single),'');
v.start(c,lineup,0);
assert.equal(c.active.service,0);
assert.equal(c.active.lineups[0][0],'1');
v.award(c,0);assert.equal(c.active.lineups[0][0],'1');
v.award(c,1);assert.equal(c.active.service,1);assert.equal(c.active.lineups[1][0],'8');assert.equal(c.active.rallies[1].serverNumber,'1');assert.equal(c.active.rallies[1].nextServer,'8');
v.award(c,0);assert.equal(c.active.lineups[0][0],'2');
assert.equal(v.undo(c),true);
assert.equal(c.active.service,1);assert.equal(c.active.lineups[0][0],'1');
v.stat(c,1,'8','serve','ace');
v.stat(c,0,'2','reception','r3');
v.stat(c,0,'1','attack','kill');
const agg=v.summary(c);
assert.equal(agg[1].aces,1);assert.equal(agg[0].kills,1);assert.equal(agg[0].attempts,1);
assert.equal(agg[0].receptionSum,3);assert.equal(agg[1].sideout.total,2);assert.equal(agg[1].sideout.won,1);
const before=c.active.lineups[1][1];v.substitute(c,1,2,'22');
assert.equal(c.active.lineups[1][1],'22');v.undo(c);assert.equal(c.active.lineups[1][1],before);
assert.throws(()=>v.close(c),/Döntetlen/);
v.award(c,1);
assert.throws(()=>v.close(c),/nem érte el/);
v.close(c,true);assert.equal(c.active.status,'closed');
assert.equal(c.active.events.length,3);
v.next(c);
assert.equal(c.active.number,2);assert.equal(c.active.status,'setup');
assert.equal(c.active.startLineups[0][0],'1');
v.start(c,lineup,1);v.award(c,0);
assert.equal(c.active.lineups[0][0],'2');
assert.equal(v.summary(c,'1')[1].aces,1);
const d=v.newCourt(2);v.start(d,lineup,0);
for(let i=0;i<24;i++)v.award(d,0);
for(let i=0;i<24;i++)v.award(d,1);
v.award(d,0);assert.equal(v.canClose(d),false);
v.award(d,0);assert.equal(v.canClose(d),true);
assert.throws(()=>v.award(d,0),/Szett már befejezhető|A szett már befejezhető/);
v.close(d);v.next(d);v.start(d,lineup,1);
for(let i=0;i<25;i++)v.award(d,1);
v.close(d);v.next(d);assert.equal(v.requiredPoints(d),15);
assert.throws(()=>v.award(d,0),/Előbb indítsd/);
console.log('PASS volleyball core: six-position rotation, serve, undo, set close/next, 26:24, 3rd-set, statistics and substitutions');
